### ISSUE TITLE
Add READMEs for each tool

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#296]
This should actually be pretty straight forward. 

Just a small little readme for each tool.

Then update dockerhub to have the readme for the tool instead of the main repo to make it look nice.

**Comment by k-florek** [comment]
I like this idea. What about a small template README that could be used as starting point?

**Comment by kapsakcj** [comment]
Agreed, I like the idea too. 

Just not sure how to replace the current READMEs on all the dockerhub repos since they all display the main `/README.md` instead of tool specific READMEs.

Once a dockerhub repo is linked to GitHub and an image is built using the dockerhub auto-build feature, then the README is displayed on dockerhub. Just need to see if we can point dockerhub to tool-specific READMEs

**Comment by erinyoung** [comment]
I just found some documentation on getting a specific readme uploaded into dockerhub for a container at https://github.com/docker/build-push-action/blob/master/docs/advanced/dockerhub-desc.md and https://github.com/peter-evans/dockerhub-description: 

Specifically, 
```
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: user/app
          readme-filepath: ./path/to/README.md
```

I'm going to be testing this today/_soon_ to see if it works
